# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('types', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('floor', models.CharField(max_length=255)),
                ('elevator', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('log', models.FloatField()),
                ('lat', models.FloatField()),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'poll_info',
            },
        ),
    ]
